spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          validation:
            mode: none
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:javaapi
    driver-class-name: org.h2.Driver
    username: user
    password: password
exapi:
  url: https://www.metaweather.com/api/location/1118370/
