apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minikube
commonLabels:
  seg: local
  cls: minikube
  env: dev
bases:
  - ../../base
patchesJson6902:
  - target:
      kind: Ingress
      name: java-api-ingress
      version: v1beta1
      group: networking.k8s.io
    path: ./ingress.patch.yaml
  - target:
      kind: Service
      name: java-api-service
      version: v1
    path: ./service.patch.yaml
secretGenerator:
  - name: tls-secret
    # you can define a namespace to generate
    # a secret in, defaults to: "default"
    namespace: minikube
    files:
      - tls.crt=./tls/tls.cert
      - tls.key=./tls/tls.key
    type: "kubernetes.io/tls"
