apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
commonLabels:
  seg: dev
  cls: dev
  env: dev
bases:
  - ../../base
patchesJson6902:
  - target:
      kind: Ingress
      name: java-api-ingress
      version: v1beta1
      group: networking.k8s.io
    path: ./ingress.patch.yaml
