apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
commonLabels:
  seg: prod
  cls: prod
  env: prod
bases:
  - ../../base
patchesJson6902:
  - target:
      kind: Ingress
      name: java-api-ingress
      version: v1beta1
      group: networking.k8s.io
    path: ./ingress.patch.yaml
